apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:M+YuP/qW,iv:9990STgf9NIXhWcgUL7rnYQHj/eJlueq1RjQRxA2w9Q=,tag:WpAP5AxhukJdnfFu4HYkhw==,type:str]
    password: ENC[AES256_GCM,data:2hn4RLqW,iv:PLG3/a1npPxGlvgtuxJqCSPGQzq4pgBc/T7pJe9STLo=,tag:riWAn90J87PLiQpXkCt+5A==,type:str]
sops:
    age:
        - recipient: age1gdl7su5ndt5a6v03npmmkh7lv63waz9wsstg89gwnk4uv3h9zdqsfkuz00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdm5YZXpKUDV5Rlp6aUpQ
            WlduWVhDbGdTTDZ5aTF2cTZtdUJXTEhLVHc0ClBQMlNXbHJqeGlMM1dGcUduUWlE
            TjF0TzJxZUNobDM2RTFramQzNW4vVU0KLS0tIGkwMy8zRDdoS1ZnWkU4amZiTllU
            bU1tZ3dHaTV5SWxOaWVaV052aVdIekkKjkayt/8J2Xob5hxQblVuQMsvMcD8Wmll
            KuaW81M9qfl+ZY8raO35YKlDCIuHWksBVip++8zVCR3jGdvSl0nN1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T04:53:55Z"
    mac: ENC[AES256_GCM,data:VPEnObpp5hx3pyVqtHKhCk3A/tqIntSZdOJApN1mVpF8FH23U1Je8qfIvRcRxGvxZtFuNOrsdFDLhybvDHVvpJ7B5DrK5j0Tb+Xbujoa5XIhhk8I4RDhkK6odS/BsN7N6Q2JIwOuwm4SUYvmMgv5JRF7ll2B8rq4E/7SDTif99M=,iv:L12tnqgUhzile+Cl6lVRFAGePkBgFoP3w+b5QGXCkMk=,tag:yWd/hPzHGBV6Jf7HeiEU9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
