apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:rZ47JiRk,iv:xQoJ9rZppkph76eTEj6sIf0bsmMsrID6L4kZB92hsJw=,tag:C9WLSAqtzkjmIKv884SBCg==,type:str]
    password: ENC[AES256_GCM,data:bsd5rD6V,iv:Lc5foVgZe7kY9jgMlTx3/DTXa0LxRSdQ/YMF64zQqa4=,tag:nPP6CCxCrumzZcEBLN92wA==,type:str]
sops:
    age:
        - recipient: age1mj5lawjurw6ax9c57x67rf5hp9el89l4p97wfu5zavglhap9ca9qnk0dn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMFZ5OVBuWWZEVmlkbmlp
            akIra1dxcVU3clZoOERmeGNNUXk0SHdkRkV3ClZLMUVBNkxBSlVkU1h3V29zN3FQ
            MXhOcTBCeHVIZ2dnMXhWcFFhWVdlYmcKLS0tIDEvSXZmWmMxbXh3bndqKzhibFRl
            Rm1SeU52VEFjL0hNUGpMZFRiZWtOOUEKCvCxhpK1oUTK/cQLACctEZl0eYLzvX79
            vU6tbfNu04glFr7YKSiTHe1tfzDaUsQgtTaNccFegd6fm1SOc+D6JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T11:16:10Z"
    mac: ENC[AES256_GCM,data:PQKUtTcKlXxZcs2WQo+N2FesIZ0slnwpU2uEwOWczLHlQe02hphQShqXS1aMYwZ+pSoBWNO8yuhmzPm7YSDQFqDwRa6PTVxHFAylQhR3Bkm9fGBR9tH9RoQ6HNZFRh9q155mUrtfVSod3j89jNWSltYQo/8AGd+Re1m19il+IPA=,iv:F6VFej+22vb96MewJN5C6glrrYAGY/ItTF+5WCMQUxk=,tag:1eXttyWMxVu7+LM9CanT4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
