apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XrMa9GzX,iv:5BJAkktOfbHXabxB+EFxxXk1EOMUyvAOp6LbKZpYooM=,tag:F31bksTkNGvGRft9+oMvmA==,type:str]
    password: ENC[AES256_GCM,data:wB3xGOIQ,iv:fxN9mbv5gUIFxm8xSJOvgXvPcFCiK3C8JHP+f3WNNZk=,tag:inhqQgCyeW5AKcivv6UinQ==,type:str]
sops:
    age:
        - recipient: age1mj5lawjurw6ax9c57x67rf5hp9el89l4p97wfu5zavglhap9ca9qnk0dn4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb3JVS0s2RERsS3pYL2ZU
            RFB5aTY4L0EvL2tpajRab0hYYk9LVXhnYW5nCkFxMmhNVFB1c3EvYTh3eS9jc0Q2
            SjJKL3ZzaWMzNlVXUXZzTFpJL0RwNXMKLS0tIEtqOWgxNUJ2UENvUlFFdHlsVUNY
            Q1FuV0hNOWxoQ0orU1ByenJsZkdES3cKAPSGp8cKdnIFeaJjQ5YSLlgtGEldJxKs
            NKFWizvTuta/Z/h5FKrAsm1cQbhyY3dBl236atmrT2fpdgnxlEFdEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T10:34:58Z"
    mac: ENC[AES256_GCM,data:J4MAMbeVxd/+ptlENmTgeSEVTY+woUumsFRYG83fqk5ii0OZKvR4eWK8hGr8MTCikz8iTVSuCWfivW4sj++hlw6zq1fbTSdNltGVeMyt/kFd2R9WQwPBu6dp33s3QJZc7vOgK0tsGiuHQ/L77NRoCJdC4ydePh0+/ZU0pPl37TQ=,iv:RttmTz2hVBH3G/JIkbTPE2oBj700D9DxnuI4IQ6O/rA=,tag:t1a1mfcJUY81T0ChJ7cD1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
